### PR TITLE
Issue 41

### PR DESCRIPTION
**Pull request by shroffk**
Addressing the issue tickets #41 #42 

@kasemir @georgweiss

### CODE REVIEW

**Comment by kasemir** [comment]
Good, thanks.

Would you also consider the VEnum handling of invalid index #45 for the upcoming release?

**Comment by shroffk** [comment]
I was reading that Issue.

When you say invalid index you mean there is no valid associated label or there are no labels.

I feel in such cases all other labels should be discarded and the VEnum and VEnumArray should behave as VInt and VInatArray.

I am not sure how best to report this...maybe I will override the toString() to make a note of this exceptions?

What say

**Comment by kasemir** [comment]
Yes, there are labels like [ A, B, C ], but the numeric value might be 42.

That is of course wrong, should never happen, but it does surprisingly often at our site.
Many of the PVs behind "LEDs" look like that.

I would like to see this represented as a VEnum that has the normal labels  [ A, B, C ], a numeric value of 42, and yes, the toString() or VEnum.getValue() which returns a string should show something like "<42>" or "Invalid enum 42", so it's somewhat obvious when displayed in a text field.

> I feel in such cases all other labels should be discarded
No, to debug this you do want to see the labels, for example in probe, so you know the valid range.
You also want to see the number, because you need to figure out how it came up with THAT number.
Turning into a VInt hides the issue.

**Comment by shroffk** [comment]
Just a thought...would it be ok, if the exception thrown returns the incorrect index value 
i.e.
```VEnum index :42 must be within the label range [1, 2, 3]```   

Couldn't the boolean widget handle this exception and display the above message with the information of the incorrect index and the expected range.

If we allow the creation of a VEnum with an invalid index then the other methods will now have to do the index checking in order to avoid IndexOutOfBound exceptions.

**Comment by kasemir** [comment]
The problem with throwing an exception is that you loose the value.
It's not archived, it doesn't show up as an alarm, ...
Simply dropping the value when trying to wrap it as a VEnum is bad.

Operationally, I need an 'enum' with numeric value outside the range to be passed on, so it's archived, used as an alarm, plotted by using the numeric value.
Only a UI client that wants to display the enum as a label has a problem with the missing label, and it can show that as "<47>" or "Index 42 is outside of label range" etc.

Also consider reading SomeRecord.STAT where you might even have a valid enum with numeric value, but Channel Access DBR_CTRL_ENUM cannot provide all the matching labels.

**Comment by shroffk** [comment]
Ok, 
I have address the above VEnum requirement

**Pull request merged**
