### PR TITLE
7.0.3

### PR DESCRIPTION
**Pull request by shroffk**
@ralphlange 
Preparing 7.0.3 release for both open jdk8 and open jdk11

### CODE REVIEW

**Comment by ralphlange** [comment]
Yippieh!

**Comment by shroffk** [comment]
@ralphlange can you have these fixes verified and then you can merge in preparation for the 7.0.3 release

**Comment by ralphlange** [comment]
Not easy.
(One specific Jenkins builder is the only machine with jdk11 that we have; I need to re-package i.e. create an update of the CODAC Core System module to get the code built there.)
Will try tomorrow.

**Comment by shroffk** [comment]
no rush...

**Comment by ralphlange** [comment]
Sure, but I have two weeks vacation starting Monday.

**Comment by ralphlange** [comment]
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project epics-util: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListBoolean.java:21: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListBoolean.java:31: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListNumber.java:23: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListNumber.java:33: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListNumber.java:43: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListNumber.java:53: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListNumber.java:63: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/src/main/java/org/epics/util/array/ListNumber.java:73: error: tag not supported in the generated HTML version: tt
     *         (<tt>index &lt; 0 || index &gt;= size()</tt>)
                ^
[...]
```

**Comment by ralphlange** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project epics-util: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - Error fetching URL: https://docs.oracle.com/javase/8/docs/api/
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/target/apidocs' dir.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project epics-util: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - javadoc: error - Error fetching URL: https://docs.oracle.com/javase/8/docs/api/

Command line was: /usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/target/apidocs' dir.

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - javadoc: error - Error fetching URL: https://docs.oracle.com/javase/8/docs/api/

Command line was: /usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/target/apidocs' dir.

	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.failOnError(AbstractJavadocMojo.java:6082)
	at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:192)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.reporting.MavenReportException: 
Exit code: 1 - javadoc: error - Error fetching URL: https://docs.oracle.com/javase/8/docs/api/

Command line was: /usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/build/workspaces/bug11142-openjdk11/m-epics-java/base-7.0.2/epics-util/target/apidocs' dir.

	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeJavadocCommandLine(AbstractJavadocMojo.java:5188)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:2075)
	at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:188)
	... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[...]
```

**Comment by shroffk** [comment]
Is the URL blocked?

**Comment by ralphlange** [comment]
Well, obviously our builders have no internet access.

**Comment by shroffk** [comment]
With java 11 there are pieces that were available in java 8 that have been removed. Hence there is the maven based linking on to them.

Can you run your builds by skipping the javadoc's build?

**Comment by ralphlange** [comment]
I don't understand. Why does the build need to fetch the URL in order to set a link?

**Comment by ralphlange** [comment]
The build gets further.
Now it hangs at the bundle, as the updated versions of related POMs are not in our artefactory cache yet. Working on it...

**Comment by ralphlange** [comment]
Maven builds and our cybersecurity requirements, i.e. pulling everything from the outside world and having no access to the outside world, don't play well together.

**Comment by ralphlange** [comment]
OK, my local build went through.
Now the artifactory should have cached all required POMs. Restarting the Jenkins build.

**Comment by ralphlange** [comment]
Better than disabling javadoc altogether:
`<isOffline>true</isOffline>`

Builds are fine now.
Merging.

**Pull request merged**
