### PR TITLE
merge git submodules back into main repo

### PR DESCRIPTION
**Pull request by shroffk**
Restructuring the repo to move some git sub modules back into the main repo.

### CODE REVIEW

**Comment by shroffk** [comment]
Todo:
Release tags need to be refactored.
The release tags for the pvaccess, pvdata, and normativeTypes are on different branches...how should they be moved.

**Comment by shroffk** [comment]
There is no code change...all these commits are from the existing master branch of these projects

**Comment by shroffk** [comment]
@mrkraimer are you ok with this? I have not moved the pvaclient and database modules cause I was not sure what your plans are for them.

**Comment by ralphlange** [comment]
Can you do a test merge and push the result somewhere visible? (Or is that equivalent to shroffk-master?)
Looking at single commits doesn't work as a base for reviewing.

**Comment by ralphlange** [comment]
Does @gcarcassi have any comments?

**Comment by gcarcassi** [comment]
Yes

**Comment by ralphlange** [comment]
So? What do you want to add?

**Comment by shroffk** [comment]
created a branch Issue_7

**Comment by gcarcassi** [comment]
I want to add "Poisson d'Avril" and "Happy Easter"! :-P
Once Kunal is done with this change, I'll be integrating the modules that I am working on my branch so that they all inherit from the root pom.

**Comment by shroffk** [comment]
Moved bundleJava into the epicsCoreJava repo

**Comment by ralphlange** [comment]
How are we going to handle the tags?

**Comment by shroffk** [comment]
> How are we going to handle the tags?


https://docs.google.com/document/d/1Oe6aDGxId6R1nANHD1Kxs9tH7caE832eULO6JueX1YA/edit#

**Comment by ralphlange** [comment]
Have you moved a copy of the current status to epics-rip? Updated the submodules so they point to the correct URLs? Did a test check-out of an old tag to make sure we don't tell BS in this readme?

**Comment by shroffk** [comment]
I have not moved...not sure what should happen first. The PR or the move.
I had assumed we would simply transfer ownership to epics-rip

**Comment by anjohnson** [comment]
Transferring ownership causes Github to set up redirects at the old URLs, and also moves all of the issues and PRs as well. That might not be what you want, unless you're going to rename the merged result as well (this would probably be the time to change the name if you do want to do that though).

**Comment by shroffk** [comment]
I can fork the above repo's into epics-rip and then remove them from epics-base after moving the appropriate issues onto epicsCoreJava. 

@ralphlange could you help with the refactoring of the gitsubmodule paths

I am tempted with remove the "Java" from all the names. Does anyone else agree with this or feels strongly about this? @kasemir @mrkraimer @mdavidsaver @ralphlange

**Comment by shroffk** [comment]
ok @ralphlange no name change now...let us just close this PR for now.

**Comment by shroffk** [comment]
I have forked all the pertinent repos to the epics-rip organization.
Here are the links..
https://github.com/epics-rip/pvDataJava
https://github.com/epics-rip/pvAccessJava
https://github.com/epics-rip/normativeTypesJava
https://github.com/epics-rip/bundleJava

**Comment by ralphlange** [comment]
Update: I was playing around with this a bit. This is not as trivial as it seemed in the first place. Hm, well, maybe it is.

Submodule URLs are part of the repository. i.e. past releases will always point to the old URLs. Changing URLs in the repository needs a commit thus does not work with old releases.

Renaming the moved repositories is not advisable. (See above comment. It might also not work with the redirects generated by an ownership change.)
Renaming the merged parent result could be done as it does not change much. (Everyone will have to use the new name for the parent repo; embedded names of submodules will stay the same.)

I can see two options:
1. **Forking the existing repos** into epics-rip (as it is done now). Existing issues and pull requests stay at the old place. Checking out an older version needs client side configuration (rewriting URLs for the moved repos). That setup needs to be documented and tested. What are we doing with the old repos? Delete them? (What about the issues and PRs then?)
2. **Changing ownership of the existing repos**. This will setup Git and URL redirects, so that checking out old releases should work without client side changes. It will move existing issues and PRs, so that they stay around for examination and archiving. It will make the existing repos disappear, so they don't confuse people.

I would say 2. seems to be the better option.
What do you say? @anjohnson @shroffk @berryma4 @mdavidsaver

**Comment by anjohnson** [comment]
I agree that changing the repo ownership is the better solution. I almost wrote that as a comment yesterday but got distracted...

**Comment by shroffk** [comment]
I had initially suggested option 2. so I think I will come back to supporting it :)

**Comment by ralphlange** [comment]
So, yes, please go ahead.
Merge, remove the forks in epics-rip, transfer ownership of the retired repos to epics-rip.

**Comment by georgweiss** [comment]
I'm not on the review list, so I'll just ask a question: are all Java models to be found under https://github.com/epics-base/epicsCoreJava once the PR is merged?

**Comment by ralphlange** [comment]
All modules that are affected by the merge, yes.

**Comment by ralphlange** [comment]
The main goal is - for this set of closely related modules - being able to do PullRequests that concern multiple modules.

In the existing separate repo layout, that used to be a set of PRs (one for each repo), and no CI can do automated multi-PR builds across repositories.

**Comment by georgweiss** [comment]
I'm a bit confused... Is the merge completed? A Maven build shows that the pom file is missing from four submodules.

**Comment by ralphlange** [comment]
For which modules? Are you sure you checked out the remaining Git submodules recursively?

**Comment by ralphlange** [comment]
Only the core modules (that are closely coupled) have been merged. The loosely coupled modules (like client and server helpers and examples) stay in separate repos and are linked using Git submodules.

Please do a full recursive checkout with submodules, and all will compile fine. (Works for me and Travis.)

**Pull request merged**
