### PR TITLE
setup CI for jdk 8 and 9

### PR DESCRIPTION
**Pull request by shroffk**
#13 and #16

### CODE REVIEW

**Comment by shroffk** [comment]
@mrkraimer 
It seems like there are errors in the pvDatabaseJava and pvClientJava. 
These errors are related to the html encoding used to create the javadoc's

```
[ERROR] Exit code: 1 - /home/travis/build/epics-base/epicsCoreJava/pvDatabaseJava/documentation/pvDatabaseJava.html:163: error: self-closing element not allowed
```

@georgweiss worked recently on fixing similar errors for the main modules. 
https://github.com/epics-base/epicsCoreJava/pull/14
Could you copy these changes so that we can enable CI against java 8, 9, and 10

**Comment by ralphlange** [comment]
What about merging this and restart the PR build(s) for Georg's changes?!

**Comment by georgweiss** [comment]
Please merge PR https://github.com/epics-base/directoryService/pull/2 to resolve this.

**Comment by shroffk** [comment]
@georgweiss thanks...I did accept the PR and it seems like it has solved the problem

**Comment by shroffk** [comment]
In preparation for moving the epics core projects to java 10+ the CI was updated to run on open and oracle versions of java starting from 8 to 11

At the last build all problems related to the javadoc production have been resolved.
https://travis-ci.org/epics-base/epicsCoreJava/builds/433584801

The only open issue is that openjfx is no longer available for trusty. It is available for xenial and bionic distributions of ubuntu.

**Comment by shroffk** [comment]
@georgweiss @ralphlange I finally have the CI builds succeeding.
Some things are not perfect, see above comment...but I think for the time being this can be merged.

Should these commits be squashed??

**Comment by ralphlange** [comment]
Yes, Please squash and merge.

**Pull request merged**
