### PR TITLE
Updated pvdata

### PR DESCRIPTION
**Pull request by shroffk**
Have to wait till PR#18 is merged before this can be merged.

### CODE REVIEW

**Comment by georgweiss** [comment]
Does not seem to build on Java 10 (several issues).

As for technical matters, I have insufficient experience with the code to say anything clever. However, I do have some comments in regards to VImage related classes: 
1) Is the VImageType enum supposed to cover all relevant permutations of properties like colour space,   number of bytes per pixel and others? If so, why not use a class that encapsulates these properties?
2) In VImgeDataType, why is there a need for a string type? Plus, the methods in the class are tightly dependent on the order in which the values appear in the source code. As an alternative, one could maybe consider an integer (or short) property in the enum in order to not depend on the ordinal, e.g. pvBoolean(0), pvByte(1), pvShort(2) etc.

**Comment by shroffk** [comment]
> Does not seem to build on Java 10 (several issues).

The master itself is not building on jdk10 as yet, have expanded the scope of the 
 PR 17 https://github.com/epics-base/epicsCoreJava/pull/17


> Is the VImageType enum supposed to cover all relevant permutations of properties like colour space, number of bytes per pixel and others? If so, why not use a class that encapsulates these properties?


> In VImgeDataType, why is there a need for a string type? Plus, the methods in the class are tightly dependent on the order in which the values appear in the source code. As an alternative, one could maybe consider an integer (or short) property in the enum in order to not depend on the ordinal, e.g. pvBoolean(0), pvByte(1), pvShort(2) etc.

The class was based on the org.epics.pvdata.ScalarType , I wanted to keep it as similar as possible so that client code dealing with Types would remain the same.
I will ask anyone if it makes sense to keep the pvString, else we could consider to remove it.

Now that I look at it in detail, I agree with you that the heavy use of ordinal is rather unfortunate. 
Ideally I would feel that the enum should be able to tell you if the type is a primitive, an integer, a unsigned value, etc....without having to check the ordinal.
However, this class was designed to match org.epics.pvdata.ScalarType I would like to keep them the same...we should consider fixing the `org.epics.pvdata.ScalarType` but that would require checking up with the other developers. This can be a discussion topic for the Aug14th meeting.

**Comment by georgweiss** [comment]
OK, I admit I have not inspected the commits in detail, but I think that we should try to spread the word that any new code should be Java 10 compliant. My impression is that Javadoc stuff that needs most attention.

**Comment by georgweiss** [comment]
I was under the impression that my fixes for Java 9+ were merged already to master. Can you please clarify?

**Comment by shroffk** [comment]
@georgweiss I too was under the impression that all your PR's have been merged.

**Comment by shroffk** [comment]
@georgweiss it seems like the javadoc issues are now with https://github.com/epics-base/exampleJava I will request Marty to have a look at it

**Comment by shroffk** [comment]
@mrkraimer I wanted you to look at the code changes here and let us know if you see any glaring problems.
If you look at the pvData code you will notice the use of the `PVNumberArray` interface instead of the `PVScalarArray`...the `PVNumberArray`  does the transformation, gives access to the array elements without requiring copy, etc...

@georgweiss 
Can we merge this and open a new issue ticket about the `VImageType` and its use of ordinals. We will not release epicsCoreJava until we resolve this.

**Comment by mrkraimer** [comment]
Look OK to me.
Go ahead and merge.

**Comment by georgweiss** [comment]
Go ahead and merge.

/Georg

**Pull request merged**
