### PR TITLE
Backport of Epics to Java 1.5

### PR DESCRIPTION
**Pull request by george-mcintyre**

### CODE REVIEW

**Comment by kasemir** [comment]
Can you preserve the line endings, otherwise the change looks too large.

I'm not 100% convinced we can enforce compatibility with 1.5.
We do want to support `Instant` for time stamps and not go back to our own timestamp with seconds and nanoseconds.
Matlab forces us to stay with 1.8, but what's tying us to 1.5?

**Comment by shroffk** [comment]
@george-mcintyre 
We are already struggling with complications of supporting the EPICS core java libraries for both java 8 and java 11.
Can you elaborate on the reason for support the epics core stack on java 5?

Like Kay mentioned, we really want to use `Instant` which can be easily used in other java applications. Additionally we have been incorporating streaming API's. All of this would result in a alot of rewriting of other code as well as make maintenance more difficult.

**Comment by george-mcintyre** [comment]
Hi @shroffk , @kasemir 

I forked the repo and I left the remote origin upstream still pointing here so pushes to my fork are coming here for merging.  That was not my intention.  I am really sorry and embarrassed :( 

Please ignore this pull request and discard changes.  

I made the changes because I need to have EPICS 7 running on OpenVMS 8.3 in Alpha architecture which only has Java 1.5 available.  I can't get the C++ working either as the OS only has C-98 and EPICS requires C-11.  

I am not expecting anyone else to use this work (Unless of course they are in the same predicament).  Please accept my apologies!

Regards
/G

> @george-mcintyre
> We are already struggling with complications of supporting the EPICS core java libraries for both java 8 and java 11.
> Can you elaborate on the reason for support the epics core stack on java 5?
> 
> Like Kay mentioned, we really want to use `Instant` which can be easily used in other java applications. Additionally we have been incorporating streaming API's. All of this would result in a alot of rewriting of other code as well as make maintenance more difficult.

**Comment by kasemir** [comment]
While I haven't heard about OpenVMS in a while, it's possible that you're not alone, that others out there would also like to use Java and Channel Access on it, and are thus restricted to Java 1.5.

But I appreciate that you agree with moving forward with the general source base.

Would it be practical for you to simply work off an older branch, maybe cherry-picking select bug fixes? Maintaining a more elaborate back port of "everything" seems way too hard, especially since new Linux computers aren't that expensive ;-)

**Comment by george-mcintyre** [comment]
Yeah, I've recreated the "fork" correctly here: https://github.com/george-mcintyre/epics-core-java-backport-1.5 so now the changes are not going to affect the general source base! :). The changes that have been made are with a view to them being temporary - not more than a few years.  Java 1.5 is unsupported, contains no security fixes etc.  So we don't want to encourage people not to upgrade!

The code there compiles and runs all tests successfully if you follow the instructions contained in the `README.md` under the `backport-java-1.5` subdirectory.  Mainly have to run Maven in JDK 1.8 - nothing else will work. 

I'm currently testing it on OpenVMS right now and can let you know how it goes if you're interested.    

> While I haven't heard about OpenVMS in a while, it's possible that you're not alone, that others out there would also like to use Java and Channel Access on it, and are thus restricted to Java 1.5.
> 
> But I appreciate that you agree with moving forward with the general source base.
> 
> Would it be practical for you to simply work off an older branch, maybe cherry-picking select bug fixes? Maintaining a more elaborate back port of "everything" seems way too hard, especially since new Linux computers aren't that expensive ;-)

**Pull request closed without merging**
