### PR TITLE
Issue 23

### PR DESCRIPTION
**Pull request by shroffk**
#23 @georgweiss this is so that we can start stress testing the gp client.
This PR added an initial implementation for the channel access datasource.

### CODE REVIEW

**Comment by shroffk** [comment]
A lot of the datasource is derived from the existing pvmanager ca datasource. However it is simplified where possible.

**Comment by georgweiss** [comment]
Sorry for my late reply...
I have but one question related to 7dac5b7: any consequences to consider if connection wait timeout is increased? Guess 50 -> 100 ms is not a big deal, but should this instead be an input/configuration parameter?

**Comment by shroffk** [comment]
The connection timeout is a parameter defined at the time of creation of the channel.
In the above commit I just changed it for the purposes of having the tests run properly on travis.

**Comment by georgweiss** [comment]
OK, sloppy reading on my behalf, it's a test case after all. 
Won't happen again...

**Comment by georgweiss** [comment]
No other comments, better keep silent.

**Comment by shroffk** [comment]
Ha...no...it is great someone is reading through things :)

I am hoping to close this as soon as possible since kasemir has discovered versioning issues on the master branch.

Should I go ahead and merge this so that claudio can also start using this in openxal

**Comment by georgweiss** [comment]
Go ahead.

**Pull request merged**
