### PR TITLE
Issue 51

### PR DESCRIPTION
**Pull request by shroffk**
Addressing the synchronization issue pointed out in Issue #51

### CODE REVIEW

**Comment by georgweiss** [comment]
I could be wrong, but frankly I do not recall changing anything with respect to synchronization. Can you point to any example where my commit (of June 12 2018) does?

**Comment by shroffk** [comment]
hmm... I am not sure how to create links from PR diff

image

but...here is one example that matej was talking about

**Comment by shroffk** [comment]
Let me know if I have misunderstood something here

**Comment by georgweiss** [comment]
OK, I see your point.
I replaced the org.epics.pvaccess.util.IntHashMap with a HashMap constructed from a call to Collections.synchronizedMap(). Reason for the replacement is that in earlier Java versions there was no support for Map collections keyed on primitives. 
Now since the created HashMap is thread safe I could not see the point of the synchronizations in this example.
Maybe I have misunderstood something?

**Comment by shroffk** [comment]
I think for the synchronized map during iterative operations we would still have to synchronize that. thus the synchronization around the for loop...
```
       synchronized (channels) {
		for(SearchInstance searchInstance : channels.values()) {	     
			searchInstance.getUserValue().set(BOOST_VALUE);	
		}
        }
```


```
synchronized (channels) {
    if (channels.size() == 0)					
        return;
    sis = new SearchInstance[channels.size()];
    channels.values().toArray(sis);
}
```

I think in this example, Matej wants all the operations to happen in a synchronized block...so the creation of the sis array using the channels.size() and the subsequent population of the array using channels.value.toArray() should be in the same syncrhonization block to ensure another thread does not modify the values inbetween the reading of the size and the actual population.

**Comment by georgweiss** [comment]
Agree, your comments make sense. Actually, since iteration should be synchronized anyway, there is probably no gain in constructing the Map from Collections.synchronizedMap(), but rather use a plain HashMap and synchronize where needed.

**Comment by shroffk** [comment]
We can explore that, but for the time being I feel leaving the synchronized maps is fine....cause this would remove synchronized blocks where we are just making a single call. 
In general I feel I might have over done it in some classes where both the method and the map is synchronized...but I am worried to remove the synchronization on the maps.

**Pull request merged**
